import { z } from "zod";
import { LIMITS } from "../constants/index";

// Upload validation
export const uploadSchema = z.object({
  file: z.instanceof(File).refine(
    (file) => file.size <= LIMITS.MAX_FILE_SIZE,
    { message: `File size must be under ${LIMITS.MAX_FILE_SIZE / (1024 * 1024)}MB` }
  ),
});

// Scan job
export const scanJobSchema = z.object({
  artifactId: z.string().uuid(),
  userId: z.string().uuid().nullable().optional(),
  status: z.enum(["queued", "processing", "completed", "failed", "timed_out"]).default("queued"),
  priority: z.number().int().min(0).max(10).default(0),
});

// Finding
export const findingSchema = z.object({
  scanJobId: z.string().uuid(),
  artifactFileId: z.string().uuid(),
  ruleId: z.string().uuid().nullable().optional(),
  category: z.enum(["loader", "propagator", "exfil", "host_abuse", "obfuscation", "ioc_match"]),
  severity: z.enum(["critical", "high", "medium", "low", "info"]),
  confidence: z.number().int().min(0).max(100),
  title: z.string().min(1).max(500),
  evidenceSnippet: z.string().optional(),
  decodedContent: z.string().optional(),
  extractedUrls: z.array(z.string().url()).optional(),
  extractedDomains: z.array(z.string()).optional(),
  lineNumber: z.number().int().positive().optional(),
});

// Verdict
export const verdictSchema = z.object({
  artifactId: z.string().uuid(),
  status: z.enum(["malicious", "suspicious", "safe", "unknown"]),
  severity: z.enum(["critical", "high", "medium", "low", "info"]),
  confidence: z.number().int().min(0).max(100),
  summary: z.string().min(1).max(2000),
  reviewerId: z.string().uuid().nullable().optional(),
  autoGenerated: z.boolean().default(true),
});

// API key creation
export const apiKeyCreateSchema = z.object({
  name: z.string().min(1).max(100).trim(),
});

// Guard events (batch of up to 100)
export const guardEventSchema = z.object({
  events: z
    .array(
      z.object({
        resourceName: z.string().min(1).max(255),
        eventType: z.enum(["violation", "blocked", "alert"]),
        functionName: z.string().min(1).max(255),
        details: z.record(z.unknown()).optional(),
        serverIp: z.string().ip().optional(),
      })
    )
    .min(1)
    .max(LIMITS.GUARD_MAX_EVENTS_PER_POST),
});

// Pagination with optional severity filter
export const paginationSchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  severity: z.enum(["critical", "high", "medium", "low", "info"]).optional(),
});

// Hash reputation
export const hashReputationSchema = z.object({
  sha256: z.string().regex(/^[a-f0-9]{64}$/, "Must be a valid SHA-256 hash"),
  hashType: z.enum(["file", "archive"]),
  list: z.enum(["blacklist", "warning", "safe", "unknown"]),
  malwareFamilyId: z.string().uuid().nullable().optional(),
  source: z.enum(["community", "analyst", "auto"]),
  analystNote: z.string().max(5000).optional(),
  expiresAt: z.coerce.date().optional(),
});

// Rule creation/update
export const ruleSchema = z.object({
  name: z.string().min(1).max(255).trim(),
  description: z.string().max(2000).optional(),
  category: z.enum(["loader", "propagator", "exfil", "host_abuse", "obfuscation", "ioc_match"]),
  severity: z.enum(["critical", "high", "medium", "low", "info"]),
  pattern: z.record(z.unknown()),
  isActive: z.boolean().default(true),
});

// Review action
export const reviewActionSchema = z.object({
  verdictId: z.string().uuid(),
  action: z.enum(["blacklist", "warning_list", "safe_list", "release", "revoke", "escalate"]),
  note: z.string().max(5000).optional(),
});

// Export types inferred from schemas
export type UploadInput = z.infer<typeof uploadSchema>;
export type ScanJobInput = z.infer<typeof scanJobSchema>;
export type FindingInput = z.infer<typeof findingSchema>;
export type VerdictInput = z.infer<typeof verdictSchema>;
export type ApiKeyCreateInput = z.infer<typeof apiKeyCreateSchema>;
export type GuardEventInput = z.infer<typeof guardEventSchema>;
export type PaginationInput = z.infer<typeof paginationSchema>;
export type HashReputationInput = z.infer<typeof hashReputationSchema>;
export type RuleInput = z.infer<typeof ruleSchema>;
export type ReviewActionInput = z.infer<typeof reviewActionSchema>;
