import { db, findings as findingsTable, verdicts, hashReputation } from "@fivemtotal/db";
import { sql } from "drizzle-orm";
import type { Finding } from "./types";
import type { Severity, VerdictStatus } from "@fivemtotal/shared";

/**
 * Severity weights for confidence aggregation.
 */
const SEVERITY_WEIGHTS: Record<Severity, number> = {
  critical: 5,
  high: 4,
  medium: 3,
  low: 2,
  info: 1,
};

/**
 * Severity tier ordering (highest first).
 */
const SEVERITY_ORDER: Severity[] = ["critical", "high", "medium", "low", "info"];

/**
 * Verdict engine.
 *
 * 1. Collect all findings for the scan job
 * 2. Group by severity tier
 * 3. Highest-severity tier wins artifact-level verdict
 * 4. Confidence = weighted average of findings in winning tier
 * 5. Apply auto-quarantine thresholds
 * 6. Insert verdict row
 * 7. Auto-update hash_reputation for critical verdicts
 */
export async function computeVerdict(
  scanJobId: string,
  artifactId: string,
  scanFindings: Finding[],
  artifactHashes: { fileSha256s: string[]; archiveSha256: string },
): Promise<{
  verdictId: string;
  status: VerdictStatus;
  severity: Severity;
  confidence: number;
}> {
  // 1. Insert findings into the database
  if (scanFindings.length > 0) {
    const findingRows = scanFindings.map((f) => ({
      scanJobId: f.scanJobId,
      artifactFileId: f.artifactFileId,
      ruleId: f.ruleId ?? null,
      category: f.category,
      severity: f.severity,
      confidence: f.confidence,
      title: f.title,
      evidenceSnippet: f.evidenceSnippet ?? null,
      decodedContent: f.decodedContent ?? null,
      extractedUrls: f.extractedUrls ?? null,
      extractedDomains: f.extractedDomains ?? null,
      lineNumber: f.lineNumber ?? null,
    }));

    // Insert in batches of 100
    for (let i = 0; i < findingRows.length; i += 100) {
      const batch = findingRows.slice(i, i + 100);
      await db.insert(findingsTable).values(batch);
    }
  }

  // 2. Group findings by severity
  const grouped = new Map<Severity, Finding[]>();
  for (const f of scanFindings) {
    const group = grouped.get(f.severity) || [];
    group.push(f);
    grouped.set(f.severity, group);
  }

  // 3. Determine winning severity tier (highest present)
  let winningSeverity: Severity = "info";
  for (const sev of SEVERITY_ORDER) {
    if (grouped.has(sev)) {
      winningSeverity = sev;
      break;
    }
  }

  // 4. Compute confidence as weighted average of findings in winning tier
  const winningFindings = grouped.get(winningSeverity) || [];
  let confidence: number;

  if (winningFindings.length === 0) {
    confidence = 0;
  } else {
    const totalWeight = winningFindings.reduce(
      (sum, f) => sum + SEVERITY_WEIGHTS[f.severity],
      0,
    );
    const weightedConfidence = winningFindings.reduce(
      (sum, f) => sum + f.confidence * SEVERITY_WEIGHTS[f.severity],
      0,
    );
    confidence = Math.round(weightedConfidence / totalWeight);
  }

  // 5. Apply auto-quarantine thresholds to determine verdict status
  const { status, summary } = determineVerdictStatus(
    winningSeverity,
    confidence,
    scanFindings.length,
  );

  // 6. Insert verdict row
  const [verdictRow] = await db
    .insert(verdicts)
    .values({
      artifactId,
      status,
      severity: winningSeverity,
      confidence,
      summary,
      autoGenerated: true,
    })
    .returning({ id: verdicts.id });

  // 7. Auto-update hash_reputation for malicious verdicts
  if (status === "malicious") {
    await updateHashReputation(artifactHashes, winningSeverity);
  }

  return {
    verdictId: verdictRow.id,
    status,
    severity: winningSeverity,
    confidence,
  };
}

/**
 * Determine verdict status and summary based on severity and confidence.
 *
 * Auto-quarantine thresholds:
 * - Critical >= 70% -> malicious, write hash_reputation blacklist
 * - High >= 80% -> suspicious, pending review
 * - Medium -> suspicious, requires manual approval
 * - Low/Info -> safe with note
 */
function determineVerdictStatus(
  severity: Severity,
  confidence: number,
  findingCount: number,
): { status: VerdictStatus; summary: string } {
  if (findingCount === 0) {
    return {
      status: "safe",
      summary: "No findings detected during analysis",
    };
  }

  switch (severity) {
    case "critical":
      if (confidence >= 70) {
        return {
          status: "malicious",
          summary: `Critical findings detected with ${confidence}% confidence. Auto-quarantined.`,
        };
      }
      return {
        status: "suspicious",
        summary: `Critical findings detected with ${confidence}% confidence. Manual review recommended.`,
      };

    case "high":
      if (confidence >= 80) {
        return {
          status: "suspicious",
          summary: `High-severity findings detected with ${confidence}% confidence. Pending review.`,
        };
      }
      return {
        status: "suspicious",
        summary: `High-severity findings detected with ${confidence}% confidence. Manual review required.`,
      };

    case "medium":
      return {
        status: "suspicious",
        summary: `Medium-severity findings detected. Requires manual approval.`,
      };

    case "low":
    case "info":
      return {
        status: "safe",
        summary: `Only ${severity}-severity findings detected (${findingCount} total). Considered safe.`,
      };

    default:
      return {
        status: "unknown",
        summary: "Unable to determine verdict",
      };
  }
}

/**
 * Update hash_reputation table for malicious verdicts.
 * Adds blacklist entries for both file and archive hashes.
 */
async function updateHashReputation(
  hashes: { fileSha256s: string[]; archiveSha256: string },
  severity: Severity,
): Promise<void> {
  // Blacklist the archive hash
  await db
    .insert(hashReputation)
    .values({
      sha256: hashes.archiveSha256,
      hashType: "archive",
      list: "blacklist",
      source: "auto",
      analystNote: `Auto-blacklisted: ${severity} severity verdict`,
    })
    .onConflictDoUpdate({
      target: [hashReputation.sha256, hashReputation.hashType],
      set: {
        list: "blacklist",
        source: "auto",
        analystNote: sql`CONCAT('Auto-blacklisted: ', ${severity}, ' severity verdict. Previous: ', ${hashReputation.analystNote})`,
        updatedAt: new Date(),
      },
    });

  // Blacklist individual file hashes
  for (const sha256 of hashes.fileSha256s) {
    await db
      .insert(hashReputation)
      .values({
        sha256,
        hashType: "file",
        list: "blacklist",
        source: "auto",
        analystNote: `Auto-blacklisted: ${severity} severity verdict`,
      })
      .onConflictDoUpdate({
        target: [hashReputation.sha256, hashReputation.hashType],
        set: {
          list: "blacklist",
          source: "auto",
          analystNote: sql`CONCAT('Auto-blacklisted: ', ${severity}, ' severity verdict')`,
          updatedAt: new Date(),
        },
      });
  }
}
