export const LIMITS = {
  MAX_FILE_SIZE: 100 * 1024 * 1024,
  MAX_DECOMPRESSED_SIZE: 500 * 1024 * 1024,
  MAX_FILE_COUNT: 5000,
  MAX_ARCHIVE_DEPTH: 3,
  FREE_API_CALLS_PER_DAY: 5,
  FREE_CONCURRENT_UPLOADS: 3,
  PAID_CONCURRENT_UPLOADS: 10,
  FREE_QUEUE_DEPTH: 5,
  PAID_QUEUE_DEPTH: 50,
  SANDBOX_MEMORY_MB: 512,
  SANDBOX_CPU_TIMEOUT_S: 60,
  SANDBOX_WALL_TIMEOUT_S: 120,
  DEAD_JOB_REAPER_S: 300,
  GUARD_POLL_INTERVAL_S: 300,
  GUARD_BATCH_INTERVAL_S: 30,
  GUARD_MAX_LOCAL_EVENTS: 500,
  GUARD_MAX_EVENTS_PER_POST: 100,
} as const;

export const RATE_LIMITS = {
  UNAUTHENTICATED: { reqPerMin: 10 },
  FREE_API_KEY: { scansPerDay: 5, reqPerMin: 30 },
  PAID_API_KEY: { reqPerMin: 1000 },
  WEB_UI_SESSION: { reqPerMin: 60 },
  GUARD: { reqPerMin: 20 },
  ADMIN: { reqPerMin: 120 },
} as const;
