// @ts-nocheck

/* eslint-disable */

// This file is auto-generated by TanStack Router at build time.
// It will be overwritten when the dev server or build process runs.
// Manual edits will be lost.

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexRoute } from "./routes/index";
import { Route as LoginRoute } from "./routes/login";
import { Route as RegisterRoute } from "./routes/register";
import { Route as DashboardIndexRoute } from "./routes/dashboard/index";
import { Route as DashboardHistoryRoute } from "./routes/dashboard/history";
import { Route as DashboardKeysRoute } from "./routes/dashboard/keys";
import { Route as DashboardSettingsRoute } from "./routes/dashboard/settings";
import { Route as DashboardAlertsRoute } from "./routes/dashboard/alerts";
import { Route as DashboardScanIndexRoute } from "./routes/dashboard/scan/index";
import { Route as DashboardScanScanIdRoute } from "./routes/dashboard/scan/$scanId";
import { Route as DashboardServersIndexRoute } from "./routes/dashboard/servers/index";
import { Route as DashboardServersServerIdRoute } from "./routes/dashboard/servers/$serverId";
import { Route as AdminIndexRoute } from "./routes/admin/index";
import { Route as AdminQueueRoute } from "./routes/admin/queue";
import { Route as AdminRulesRoute } from "./routes/admin/rules";
import { Route as AdminFamiliesRoute } from "./routes/admin/families";
import { Route as AdminIntelligenceRoute } from "./routes/admin/intelligence";
import { Route as AdminAuditRoute } from "./routes/admin/audit";
import { Route as AdminArtifactArtifactIdRoute } from "./routes/admin/artifact/$artifactId";

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRoute;
      parentRoute: typeof rootRoute;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRoute;
      parentRoute: typeof rootRoute;
    };
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterRoute;
      parentRoute: typeof rootRoute;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/dashboard";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRoute;
      parentRoute: typeof rootRoute;
    };
    "/dashboard/history": {
      id: "/dashboard/history";
      path: "/dashboard/history";
      fullPath: "/dashboard/history";
      preLoaderRoute: typeof DashboardHistoryRoute;
      parentRoute: typeof rootRoute;
    };
    "/dashboard/keys": {
      id: "/dashboard/keys";
      path: "/dashboard/keys";
      fullPath: "/dashboard/keys";
      preLoaderRoute: typeof DashboardKeysRoute;
      parentRoute: typeof rootRoute;
    };
    "/dashboard/settings": {
      id: "/dashboard/settings";
      path: "/dashboard/settings";
      fullPath: "/dashboard/settings";
      preLoaderRoute: typeof DashboardSettingsRoute;
      parentRoute: typeof rootRoute;
    };
    "/dashboard/alerts": {
      id: "/dashboard/alerts";
      path: "/dashboard/alerts";
      fullPath: "/dashboard/alerts";
      preLoaderRoute: typeof DashboardAlertsRoute;
      parentRoute: typeof rootRoute;
    };
    "/dashboard/scan/": {
      id: "/dashboard/scan/";
      path: "/dashboard/scan";
      fullPath: "/dashboard/scan/";
      preLoaderRoute: typeof DashboardScanIndexRoute;
      parentRoute: typeof rootRoute;
    };
    "/dashboard/scan/$scanId": {
      id: "/dashboard/scan/$scanId";
      path: "/dashboard/scan/$scanId";
      fullPath: "/dashboard/scan/$scanId";
      preLoaderRoute: typeof DashboardScanScanIdRoute;
      parentRoute: typeof rootRoute;
    };
    "/dashboard/servers/": {
      id: "/dashboard/servers/";
      path: "/dashboard/servers";
      fullPath: "/dashboard/servers/";
      preLoaderRoute: typeof DashboardServersIndexRoute;
      parentRoute: typeof rootRoute;
    };
    "/dashboard/servers/$serverId": {
      id: "/dashboard/servers/$serverId";
      path: "/dashboard/servers/$serverId";
      fullPath: "/dashboard/servers/$serverId";
      preLoaderRoute: typeof DashboardServersServerIdRoute;
      parentRoute: typeof rootRoute;
    };
    "/admin/": {
      id: "/admin/";
      path: "/admin";
      fullPath: "/admin/";
      preLoaderRoute: typeof AdminIndexRoute;
      parentRoute: typeof rootRoute;
    };
    "/admin/queue": {
      id: "/admin/queue";
      path: "/admin/queue";
      fullPath: "/admin/queue";
      preLoaderRoute: typeof AdminQueueRoute;
      parentRoute: typeof rootRoute;
    };
    "/admin/rules": {
      id: "/admin/rules";
      path: "/admin/rules";
      fullPath: "/admin/rules";
      preLoaderRoute: typeof AdminRulesRoute;
      parentRoute: typeof rootRoute;
    };
    "/admin/families": {
      id: "/admin/families";
      path: "/admin/families";
      fullPath: "/admin/families";
      preLoaderRoute: typeof AdminFamiliesRoute;
      parentRoute: typeof rootRoute;
    };
    "/admin/intelligence": {
      id: "/admin/intelligence";
      path: "/admin/intelligence";
      fullPath: "/admin/intelligence";
      preLoaderRoute: typeof AdminIntelligenceRoute;
      parentRoute: typeof rootRoute;
    };
    "/admin/audit": {
      id: "/admin/audit";
      path: "/admin/audit";
      fullPath: "/admin/audit";
      preLoaderRoute: typeof AdminAuditRoute;
      parentRoute: typeof rootRoute;
    };
    "/admin/artifact/$artifactId": {
      id: "/admin/artifact/$artifactId";
      path: "/admin/artifact/$artifactId";
      fullPath: "/admin/artifact/$artifactId";
      preLoaderRoute: typeof AdminArtifactArtifactIdRoute;
      parentRoute: typeof rootRoute;
    };
  }
}

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LoginRoute,
  RegisterRoute,
  DashboardIndexRoute,
  DashboardHistoryRoute,
  DashboardKeysRoute,
  DashboardSettingsRoute,
  DashboardAlertsRoute,
  DashboardScanIndexRoute,
  DashboardScanScanIdRoute,
  DashboardServersIndexRoute,
  DashboardServersServerIdRoute,
  AdminIndexRoute,
  AdminQueueRoute,
  AdminRulesRoute,
  AdminFamiliesRoute,
  AdminIntelligenceRoute,
  AdminAuditRoute,
  AdminArtifactArtifactIdRoute,
]);
