import {
  pgTable,
  pgEnum,
  text,
  timestamp,
  integer,
  boolean,
  jsonb,
  index,
} from "drizzle-orm/pg-core";
import { users } from "./users";
import { scanJobs, artifactFiles, artifacts } from "./scan";
import { rules } from "./review";

// Enums
export const findingCategoryEnum = pgEnum("finding_category", [
  "loader",
  "propagator",
  "exfil",
  "host_abuse",
  "obfuscation",
  "ioc_match",
]);
export const severityEnum = pgEnum("severity", [
  "critical",
  "high",
  "medium",
  "low",
  "info",
]);
export const verdictStatusEnum = pgEnum("verdict_status", [
  "malicious",
  "suspicious",
  "safe",
  "unknown",
]);

// Findings
export const findings = pgTable(
  "findings",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    scanJobId: text("scan_job_id")
      .notNull()
      .references(() => scanJobs.id),
    artifactFileId: text("artifact_file_id")
      .notNull()
      .references(() => artifactFiles.id),
    ruleId: text("rule_id").references(() => rules.id),
    category: findingCategoryEnum("category").notNull(),
    severity: severityEnum("severity").notNull(),
    confidence: integer("confidence").notNull(),
    title: text("title").notNull(),
    evidenceSnippet: text("evidence_snippet"),
    decodedContent: text("decoded_content"),
    extractedUrls: jsonb("extracted_urls").$type<string[]>(),
    extractedDomains: jsonb("extracted_domains").$type<string[]>(),
    lineNumber: integer("line_number"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (table) => [
    index("findings_scan_severity_idx").on(table.scanJobId, table.severity),
  ]
);

// Verdicts
export const verdicts = pgTable("verdicts", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  artifactId: text("artifact_id")
    .notNull()
    .references(() => artifacts.id),
  status: verdictStatusEnum("status").notNull(),
  severity: severityEnum("severity").notNull(),
  confidence: integer("confidence").notNull(),
  summary: text("summary").notNull(),
  reviewerId: text("reviewer_id").references(() => users.id),
  autoGenerated: boolean("auto_generated").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at")
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});
